name: PIRD-env

channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - jupyter=1.0.0
  - jupyterlab>=3.1
  - matplotlib=3.4.1
  - numpy=1.20.2
  - pandas=1.2.4
  - statsmodels=0.13.2
  - seaborn
  - pmdarima
